# Generated by Django 4.1.7 on 2023-04-04 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atividadealuno',
            options={'verbose_name_plural': 'Atividade Aluno'},
        ),
        migrations.AlterModelOptions(
            name='disciplinaaluno',
            options={'verbose_name_plural': 'Disciplina Aluno'},
        ),
        migrations.AlterModelOptions(
            name='frequencia',
            options={'verbose_name_plural': 'Frequência'},
        ),
        migrations.AlterModelOptions(
            name='frequenciaaluno',
            options={'verbose_name_plural': 'Frequência do Aluno'},
        ),
        migrations.AlterModelOptions(
            name='planoaula',
            options={'verbose_name_plural': 'Plano de Aula'},
        ),
        migrations.AlterField(
            model_name='atividadealuno',
            name='nota',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='disciplinaaluno',
            name='nota',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='planoaula',
            name='metodo',
            field=models.CharField(choices=[('T', 'Teorica'), ('P', 'Prática')], max_length=1),
        ),
    ]
