# Generated by Django 4.1.7 on 2023-04-05 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_atividadealuno_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinaaluno',
            name='nota',
            field=models.FloatField(blank=True, default=0.0, editable=False, null=True),
        ),
    ]
